definitions:
  domain.CreateEmployeeRequest:
    properties:
      city:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  domain.EmployeeResponse:
    properties:
      city:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
    type: object
  domain.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  domain.UpdateEmployeeRequest:
    properties:
      city:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/employees:
    get:
      description: Возвращает список сотрудников
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.EmployeeResponse'
            type: array
        "500":
          description: внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Получить всех сотрудников
      tags:
      - employees
    post:
      consumes:
      - application/json
      description: Создает нового сотрудника
      parameters:
      - description: Данные сотрудника
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.CreateEmployeeRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.EmployeeResponse'
        "400":
          description: некорректный JSON / ошибка валидации
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Создать сотрудника
      tags:
      - employees
  /api/employees/{id}:
    delete:
      description: Удаляет сотрудника по ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: некорректный ID
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: сотрудник не найден
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Удалить сотрудника
      tags:
      - employees
    get:
      description: Возвращает сотрудника по ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.EmployeeResponse'
        "400":
          description: некорректный ID
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: сотрудник не найден
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Получить сотрудника
      tags:
      - employees
    put:
      consumes:
      - application/json
      description: Обновляет данные сотрудника по ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      - description: Данные сотрудника
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateEmployeeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.EmployeeResponse'
        "400":
          description: некорректный ID / некорректный JSON / ошибка валидации
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: сотрудник не найден
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Обновить сотрудника
      tags:
      - employees
swagger: "2.0"
